<a href="https://colab.research.google.com/github/pbannuru/NLP-ALL_STUFF/blob/main/Template_of_Transformers_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks


In [ ]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

In [ ]:
import torch 
torch.cuda.is_available()

False

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%%timeit 
classifier = pipeline('sentiment-analysis')


No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-englis

1.4 s ± 239 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit 
classifier("i love my country")

61.5 ms ± 8.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
!pip install gradio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.3 MB 1.7 MB/s 
     |████████████████████████████████| 2.3 MB 54.1 MB/s 
     |████████████████████████████████| 55 kB 3.5 MB/s 
     |████████████████████████████████| 270 kB 56.8 MB/s 
     |████████████████████████████████| 84 kB 3.4 MB/s 
     |████████████████████████████████| 112 kB 65.4 MB/s 
     |████████████████████████████████| 54 kB 2.7 MB/s 
     |████████████████████████████████| 57 kB 5.2 MB/s 
     |████████████████████████████████| 212 kB 57.4 MB/s 
     |████████████████████████████████| 84 kB 3.1 MB/s 
     |████████████████████████████████| 63 kB 2.0 MB/s 
     |████████████████████████████████| 80 kB 8.7 MB/s 
     |████████████████████████████████| 68 kB 6.6 MB/s 
     |████████████████████████████████| 46 kB 3.8 MB/s 
     |████████████████████████████████| 856 kB 51.2 MB/s 
     |████████████████████████████████| 4.0 MB 56.

In [ ]:
import gradio as gr 
def sentiment_classifier(in_text):
  return classifier(in_text) 
demo = gr.Interface(fn=sentiment_classifier,inputs='text',outputs='text')

demo.launch()

Colab notebook detected. To show errors in colab notebook, set `debug=True` in `launch()`
Running on public URL: https://21621.gradio.app

This share link expires in 72 hours. For free permanent hosting, check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x7fe2bf608050>,
 'http://127.0.0.1:7860/',
 'https://21621.gradio.app')

In [ ]:
from transformers import AutoTokenizer

In [ ]:
ckpt='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(ckpt)

In [ ]:
inputs='I love my country'

In [ ]:
tokenizer(inputs)

{'input_ids': [101, 1045, 2293, 2026, 2406, 102], 'attention_mask': [1, 1, 1, 1, 1, 1]}

In [ ]:
batch_input=['I love my country','I am pavan kumar','I work in CESC limited']

In [ ]:
out=tokenizer(batch_input,padding=True)
out

{'input_ids': [[101, 1045, 2293, 2026, 2406, 102, 0, 0], [101, 1045, 2572, 6643, 6212, 9600, 102, 0], [101, 1045, 2147, 1999, 8292, 11020, 3132, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 0, 0], [1, 1, 1, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [ ]:
type(out)

transformers.tokenization_utils_base.BatchEncoding

In [ ]:
out_tf_tensors =tokenizer(batch_input,padding=True,return_tensors='tf')

In [ ]:
out_tf_tensors

{'input_ids': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[  101,  1045,  2293,  2026,  2406,   102,     0,     0],
       [  101,  1045,  2572,  6643,  6212,  9600,   102,     0],
       [  101,  1045,  2147,  1999,  8292, 11020,  3132,   102]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [ ]:
out_pytorch_tensors =tokenizer(batch_input,padding=True,return_tensors='pt')

In [ ]:
out_pytorch_tensors

{'input_ids': tensor([[  101,  1045,  2293,  2026,  2406,   102,     0,     0],
        [  101,  1045,  2572,  6643,  6212,  9600,   102,     0],
        [  101,  1045,  2147,  1999,  8292, 11020,  3132,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
from transformers import AutoModel

In [ ]:
model_ckpt=AutoModel.from_pretrained(ckpt)
model_ckpt

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['pre_classifier.bias', 'classifier.bias', 'pre_classifier.weight', 'classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0): TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Linear(i

In [ ]:
logits=model_ckpt(**out_pytorch_tensors)
logits

BaseModelOutput(last_hidden_state=tensor([[[ 0.4521,  0.2584,  0.0448,  ...,  0.4836,  0.8697, -0.2664],
         [ 0.5710,  0.4134,  0.0491,  ...,  0.5090,  0.7748, -0.2068],
         [ 0.8872,  0.5492,  0.2826,  ...,  0.3853,  0.8563, -0.2052],
         ...,
         [ 1.1699,  0.1472,  0.3953,  ...,  0.6892,  0.3143, -0.7836],
         [ 0.1524,  0.2717, -0.0463,  ...,  0.5120,  0.7881, -0.0840],
         [ 0.3523,  0.2676, -0.0041,  ...,  0.5652,  0.6715, -0.0517]],

        [[ 0.3305,  0.2820,  0.7304,  ...,  0.2923,  0.4173, -0.0139],
         [ 0.9952,  0.3502,  0.4329,  ...,  0.2294,  0.5960, -0.1554],
         [ 0.9608,  0.7417,  0.8863,  ...,  0.1087,  0.3296, -0.0905],
         ...,
         [ 0.2397, -0.3137,  0.7742,  ...,  0.3555,  0.2912,  0.2500],
         [ 1.0750,  0.2017,  0.7271,  ...,  0.7887,  0.0205, -0.7441],
         [ 0.3020, -0.0424,  0.9516,  ...,  0.7422,  0.3442, -0.0037]],

        [[ 0.0344,  0.4058, -0.2830,  ..., -0.2490,  0.0205,  0.2575],
         [ 

In [ ]:
logits['last_hidden_state'].shape

torch.Size([3, 8, 768])

In [ ]:
batch_size,sequence_len,Hidden_state=logits['last_hidden_state'].shape
batch_size,sequence_len,Hidden_state

(3, 8, 768)

In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
model2=AutoModelForSequenceClassification.from_pretrained(ckpt)

In [ ]:
pred=model2(**out_pytorch_tensors)

In [ ]:
pred

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2268,  4.5594],
        [-3.2246,  3.5596],
        [ 2.2388, -1.8628]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
import torch 
pred_prob=torch.nn.functional.softmax(pred.logits,dim=1)
print(pred_prob)

tensor([[1.5280e-04, 9.9985e-01],
        [1.1302e-03, 9.9887e-01],
        [9.8372e-01, 1.6277e-02]], grad_fn=<SoftmaxBackward0>)


In [ ]:
model2.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [ ]:
torch.argmax(pred_prob,dim=1)

tensor([1, 1, 0])