<a href="https://colab.research.google.com/github/pbannuru/NLP-ALL_STUFF/blob/main/Transformers_using_pretrained_model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%cd /content/drive/MyDrive/Colab Notebooks

[Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks'
/content


In [1]:
try:
  from transformers import pipeline
except Exception as e:
  print(e)
  !pip install datasets transformers[sentencepiece] -q
  from transformers import pipeline

No module named 'transformers'
     |████████████████████████████████| 432 kB 9.5 MB/s 
     |████████████████████████████████| 4.9 MB 46.8 MB/s 
     |████████████████████████████████| 212 kB 61.3 MB/s 
     |████████████████████████████████| 115 kB 44.7 MB/s 
     |████████████████████████████████| 163 kB 57.4 MB/s 
     |████████████████████████████████| 127 kB 51.7 MB/s 
     |████████████████████████████████| 6.6 MB 52.3 MB/s 
     |████████████████████████████████| 1.3 MB 47.3 MB/s 


In [3]:
import torch 
torch.cuda.is_available()

False

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
from transformers import BertConfig, BertModel

In [8]:
config=BertConfig()
config

BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.22.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

In [9]:
model=BertModel(config) # this will initialize new weights and create new model architecture

In [10]:
model_with_trained_wts=BertModel.from_pretrained("bert-base-cased")

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/436M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [11]:
model_with_trained_wts.save_pretrained("./model_dir")

In [12]:
seq=['Hello','there','pavan']

In [17]:
encoded_seq=[ [ 101, 7592,  102,    0],
              [ 101, 2045,  102,    0],
              [ 101, 6643, 6212,  102]]

In [13]:
batch_input=['I love my country','I am pavan kumar','I work in CESC limited']

In [16]:
from transformers import AutoTokenizer
ckpt='distilbert-base-uncased-finetuned-sst-2-english'
tokenizer=AutoTokenizer.from_pretrained(ckpt)
out_tf_tensors =tokenizer(seq,padding=True,return_tensors='tf')
out_tf_tensors

{'input_ids': <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 101, 7592,  102,    0],
       [ 101, 2045,  102,    0],
       [ 101, 6643, 6212,  102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 1]], dtype=int32)>}

In [19]:
model_ins=torch.tensor(encoded_seq)

In [21]:
pred=model_with_trained_wts(model_ins)
pred

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.2556, -0.1481,  0.1550,  ..., -0.0625,  0.1899,  0.1530],
         [ 0.3153, -0.5242,  0.4066,  ..., -0.2606,  0.4003,  0.1643],
         [ 0.7894,  0.4261, -0.8203,  ..., -0.3892,  0.6868,  0.1498],
         [-0.0738, -0.0744, -0.1813,  ..., -0.0655,  0.3480,  0.1428]],

        [[ 0.1520,  0.2875, -0.0268,  ..., -0.3549,  0.3421, -0.1908],
         [ 0.6107, -0.4785,  0.4889,  ..., -0.5093,  0.2495, -0.0341],
         [ 0.6737, -0.0598, -0.6571,  ..., -0.2528,  0.2638,  0.0013],
         [-0.0342, -0.0930, -0.2787,  ..., -0.0959,  0.2966,  0.1469]],

        [[ 0.2300, -0.0999,  0.3977,  ..., -0.0271,  0.0230,  0.3365],
         [ 0.7307, -0.1658,  0.5551,  ...,  0.2880, -0.0038,  0.2775],
         [ 0.1212, -0.0852,  0.2506,  ...,  0.4444,  0.2747,  0.4288],
         [ 0.0971,  0.1276, -0.2120,  ..., -0.3862,  1.1606, -0.3299]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-0.5965,  0.